

spring:
  profiles:
    active: local


#front 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    encoding: UTF-8
    mode: HTML
#    prefix: classpath:/templates
#    suffix: .html
    check-template-location: true
  #jpa 설정
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#        use_sql_comments: true


#logback 설정
logging:
  config: classpath:logback-spring.xml

#mybatis 설정

mybatis:
  type-aliases-package: kr.co.climb.web.admin
  mapper-locations: classpath:/mapper/*.xml
  configuration:

    cache-enabled: false
    auto-mapping-behavior: full
    default-executor-type: reuse
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    local-cache-scope: statement
    jdbc-type-for-null: varchar
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    auto-mapping-unknown-column-behavior: warning
    #use-generated-keys: true
    #return-instance-for-empty-row: true
    default-enum-type-handler: org.apache.ibatis.type.StringTypeHandler

#upbit 설정
upbit:
  access-key: tW35LlxEgeMK3sADn849Th6k64UC3h4DCxoDxfjj
  secret-key: S4tgCUPLvlnFRJi1NQpeNN8YrEkQcYDJ0wUW6BRN

---
##################################################### LOCAL ###########################################################
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://211.47.75.102:3306/dbcoin
    username: coin
    password: pjh871107!

server:
  port: 8080
  error:
    path: /error
  servlet:
    session:
      timeout: 86400
#  forward-headers-strategy: native

#Multipart
file:
  path: C:/account/files/

site:
  baseUrl: https://localhost



---



###################################################### DEV ############################################################
spring:
  config:
    activate:
      on-profile: dev
#  h2:
#    console:
#      enabled: true
#      path: /DB
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://211.47.75.102:3306/dbcoin
    username: coin
    password: pjh871107!

server:
  port: 8080
  error:
    path: /error
  servlet:
    session:
      timeout: 86400
#  forward-headers-strategy: native

#Multipart
file:
  path: /deploy/account/files/

site:
  baseUrl: https://account-book.link

google:
  oauth2:
    baseUrl: https://oauth2.googleapis.com
    returnUrl: https://account-book.link/api/google/returnLoginResult
    grantType: authorization_code
  clientId: 946815639256-jk1ucvsupfkoo0rg6r42cht5m2btam4d.apps.googleusercontent.com
  clientSecret: TJ8xm-16M2c-T1oGBysspWL1