

spring:
  profiles:
    active: local


#front 설정
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates
    suffix: .html
    check-template-location: true
  #jpa 설정
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#        use_sql_comments: true


#logback 설정
logging:
  config: classpath:logback-spring.xml



---
##################################################### LOCAL ###########################################################
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://211.47.75.102:3306/dbcoin
    username: coin
    password: pjh871107
#  h2:
#    console:
#      enabled: true
#      path: /DB
#  datasource:
#    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      #jdbc-url: jdbc:h2:./data/testdb # ./ Project root
#      jdbc-url: jdbc:log4jdbc:h2:tcp://3.38.35.11:9094/PUBLIC;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;
#      username: test
#      password: 1234
#      maximum-pool-size: 50
#      minimum-idle: 10

server:
  port: 8080
#  port: 443
#  ssl:
#    enabled: true
#    key-store: C:/dev/ssl/keystore.p12
#    key-store-password: 'pjh871107'
#    key-password: 'pjh871107'


  error:
    path: /erro


#Multipart
file:
  path: C:/account/files/

site:
  baseUrl: https://localhost



---



###################################################### DEV ############################################################
spring:
  config:
    activate:
      on-profile: dev
#  h2:
#    console:
#      enabled: true
#      path: /DB
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://211.47.75.102:3306/dbcoin
    username: coin
    password: pjh871107

server:
#  port: 8080
  port: 443
  ssl:
    enabled: true
    key-store: /deploy/ssl/2023-07-30/keystore.p12
    key-store-password: 'pjh871107'
  error:
    path: /erro

#KCP 연동
kcp:
  conf:
    log:
      dir: /deploy/log/kcp/log
      level: 3
    gw:
      url: testpaygw.kcp.co.kr
      port: 8090
    js:
      url: https://testpay.kcp.co.kr/plugin/payplus_web.jsp
    server: false
    site:
      cd: T0000
      key: 3grptw1.zW0GSo4PQdaGvsF__
      name: KCP TEST SHOP
    module:
      type: 01
    tx:
      mode: 0
    return:
      url: https://account-book.link/pay/mo/progressPayment

#Multipart
file:
  path: /deploy/account/files/

site:
  baseUrl: https://account-book.link

google:
  oauth2:
    baseUrl: https://oauth2.googleapis.com
    returnUrl: https://account-book.link/api/google/returnLoginResult
    grantType: authorization_code
  clientId: 946815639256-jk1ucvsupfkoo0rg6r42cht5m2btam4d.apps.googleusercontent.com
  clientSecret: TJ8xm-16M2c-T1oGBysspWL1